version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "monthly"
      time: "09:00"
      timezone: "Europe/Helsinki"
    open-pull-requests-limit: 2
    ignore:
      - dependency-name: "*"
        update-types:
          - "version-update:semver-major"
    groups:
      python-minor-and-patch:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"
